[phases.setup]
nixPkgs = ["openjdk17", "maven"]

[phases.install]
cmds = ["mvn clean package -DskipTests"]

[start]
cmd = "java -jar target/customer-order-portal-0.0.1-SNAPSHOT.jar"

[variables]
JAVA_HOME = "/usr/lib/jvm/java-17-openjdk"
