[build]
builder = "nixpacks"

[deploy]
startCommand = "java -jar target/customer-order-portal-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
