FROM openjdk:17-jdk-slim

WORKDIR /app

# Copy everything
COPY . .

# Build the application
RUN ./mvnw clean package -DskipTests

# Expose the port
EXPOSE 8080

# Run the application
CMD ["java", "-jar", "target/customer-order-portal-0.0.1-SNAPSHOT.jar"]
