spring:
  datasource:
    url: jdbc:h2:mem:customer_order_portal
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  security:
    user:
      name: admin
      password: admin

server:
  port: 8080

jwt:
  secret: your-super-secret-jwt-key-that-is-long-enough-for-hs512-algorithm-and-must-be-at-least-64-bytes-long-for-security
  expiration: 86400000 # 24 hours

logging:
  level:
    com.viljandi: DEBUG
    org.springframework.security: DEBUG
